### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pintraj** [ed-rom/moodle-auth_uniquelogin#3]
I have installed your plugin and fallow the steps provided. Still the users are able to login in multi desktop with single username.

**Comment by ed-rom** [comment]
Hi,
What version of Moodle do you use?
What type of user are you using? Teacher or Student?

**Comment by pintraj** [comment]
issue is solved 
Thanks

**Comment by njcrzdrh** [comment]
Hi pintraj!
How have you solved this issue? I have the same problem and cant seem to pinpoint the reason...
Thank you!
