### ISSUE TITLE
Plug-in Kills session when forcing password change.

### ISSUE THREAD

**Issue by heather-williams** [ed-rom/moodle-auth_uniquelogin#4]
We are seeing an issue when forcing password change for users when this plug-in is enabled.

1) Force password change for your test user.
2) log in as your test user and change your password
3) once you have changed your password and hit continue on the next page you will be logged out (it kills your session).
4) then when you log back in you are redirected to user/preferences.php?userid=0&course=1 which of course is invalid and results in an error page.

I am able to replicate this behavior in Moodle versions 3.0, 3.1 and 3.2 with this plug-in installed and enabled.

There is also a message about deprecated methods: Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; auth_plugin_uniquelogin has a deprecated constructor in /mnt/code/www/moodle_prod/auth/uniquelogin/auth.php on line 26

And in 3.2 when you change your password and it redirects you to the page that says your password has been changed and gives you the continue button, a pop up comes up with an error, I'm attaching a screenshot (not sure if it's related but thought it might be helpful).
![m32_unique](https://user-images.githubusercontent.com/10454984/27489566-f67b5cec-5808-11e7-9429-2c463b1cafd1.png)

Let me know if you have questions.

**Comment by ed-rom** [comment]
Thanks for identifying the problem.
The problems reported has been solved today.

Please update the plugin.

**Comment by heather-williams** [comment]
Thank you!

**Comment by vikdcp** [comment]
i'm using last version of plugin with moodle 3.2.9 and i still got this problem, any suggestion? thanks.
